### ISSUE TITLE
Provide valid User-Agent for Nominatim

### ISSUE THREAD

**Issue by pnorman** [eileenmcnaughton/org.wikimedia.geocoder#1]
The [nominatim.openstreetmap.org](https://operations.osmfoundation.org/policies/nominatim/) states that users must "provide a valid HTTP Referer or User-Agent identifying the application (stock User-Agents as set by http libraries will not do)."

The User-Agent is currently [set to the default GuzzleHttp one](https://github.com/eileenmcnaughton/org.wikimedia.geocoder/blob/ceb86de2c0abd4b21d5ad8cf73a50f530e08509d/vendor/guzzlehttp/guzzle/src/functions.php#L135-L141). This is in violation of the usage policy.

cc @lonvia

**Comment by eileenmcnaughton** [comment]
@pnorman thank you - I have logged an issue with the upstream package to see their response

**Comment by eileenmcnaughton** [comment]
@pnorman just a quick note to say I got a quick upstream response on this so hopefully we'll be able to get from there!

**Comment by jbelien** [comment]
PR https://github.com/geocoder-php/Geocoder/pull/873 is waiting for reviewing :)

**Comment by jbelien** [comment]
Version `5.0.0` of [Nominatim provider](https://github.com/geocoder-php/nominatim-provider) was just released : https://github.com/geocoder-php/nominatim-provider/releases/tag/5.0.0

It fixes this issue ! 🎉
