### ISSUE TITLE
Fatal error: Cannot redeclare Clue\StreamFilter\register()

### ISSUE THREAD

**Issue by magnolia61** [eileenmcnaughton/org.wikimedia.geocoder#13]
Hi Eileen,
Can it be the current masters of geocoder and omnipaymultiprocessor conflict?

`Fatal error: Cannot redeclare Clue\StreamFilter\register() (previously declared in /var/www/vhosts/XYZ/webroot/sites/all/modules/civicrm_extensions/org.wikimedia.geocoder/vendor/clue/stream-filter/src/functions.php:140) in /var/www/vhosts/XZY/webroot/sites/all/modules/civicrm_extensions/nz.co.fuzion.omnipaymultiprocessor/nz.co.fuzion.omnipaymultiprocessor/vendor/clue/stream-filter/src/functions.php on line 140`

**Comment by eileenmcnaughton** [comment]
@magnolia61 hmm - maybe - I updated Geocoder to be php7 the other day & haven't looked at Omnipay vendor yet - I'll do an update though

**Comment by eileenmcnaughton** [comment]
Let's try this https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/pull/129

**Comment by magnolia61** [comment]
Hi Eileen. When I use the current master of omnipay I still get the same error. When I disable omnipay I can install geocoder correctly. Would this issue be better at the omnipay processor?

**Comment by eileenmcnaughton** [comment]
Hmm  - as long as both are using clue/streamfilter v1.4.1" they should be ok due to this fix in the package https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/commit/7c6def33914fa4e8be7aefa0dab302bbd4d425b5#diff-2cc59e34c8612ba0d2af2d945b9e5937R5
