### ISSUE TITLE
When geocoding city+state+country, geocoder is not using state for lookups

### ISSUE THREAD

**Issue by scoobird** [eileenmcnaughton/org.wikimedia.geocoder#14]
Using default configuration for U.S. addresses, no Google API (so that means most requests use Nominatim I believe). Can replicate on a clean install.

When geocoding incomplete addresses, and running proximity search on U.S. cities, we are getting inconsistent results. Example:
 
1. Enter an address of City: Madison, Country: United States, State: Wisconsin
Expected behavior: Geocode returns central point of 43.074761,-89.3837613
Observed behavior: Geocode returns 31.116041917595, -97.36932593614. (This is a street named "Madison, Temple, TX 76504")

2. now let's do Goshen, United States, Indiana
Expected behavior: Geocode returns central point of 41.5824086,-85.834366
Observed behavior: Geocode returns 42.4403646, -72.7995377 (This is Goshen village, Hampshire County, Massachusetts)

3. how about Albuquerque, US - New Mexico?
Expected behavior: 35.0841034,-106.6509851
Observed behavior: 35.0841034, -106.6509851

(There are other Albuquerque's, but no others in the U.S.)

My conclusion is that State is being tossed out in these requests. I am looking at CRM_Utils_Geocode::getValueFromResult() and I see getLocality() is the function that should be used, but I don't know where to look for how OSM is handling the request geocoder is sending it. 

Is there a configuration I can change to address this, or is this a bug? Thanks!

**Comment by agileware-pengyi** [comment]
#15 may help you out.

Agileware ref: CIVICRM-1317

**Comment by scoobird** [comment]
@agileware-pengyi yep! Thank you!
