### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by edvanleeuwen** [eileenmcnaughton/org.wikimedia.geocoder#19]
I am trying to install this extension, but on clicking install I get:

`Warning: require(/home/xxx/domains/a.xxx.nl/public_html/sites/default/files/civicrm/ext/org.wikimedia.geocoder/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php): failed to open stream: No such file or directory in require() (regel 66 van /home/xxx/domains/a.xxx.nl/public_html/sites/default/files/civicrm/ext/org.wikimedia.geocoder/vendor/composer/autoload_real.php).`

What am I missing?

Drupal 7.72
CiviCRM 5.27.1

PHP 7.3.19

**Comment by eileenmcnaughton** [comment]
Some of the files got added as a submodule rather than as files & hence were missing - this fixes https://github.com/eileenmcnaughton/org.wikimedia.geocoder/commit/d7a4ada71f1022e286e390f660324ca5930ca01e - 1.5 includes it
