### ISSUE TITLE
Where do I add the API keys?

### ISSUE THREAD

**Issue by bkeevil** [eileenmcnaughton/org.wikimedia.geocoder#20]
I can't figure out where I am supposed to add my API keys? I have keys for Google and MapQuest. I see 'Geocoder' added as a Geocoding provider under "Mapping and Geocoding" and there is an edit box for a Google Maps API key below that but I think that has to do with the "stock" geocoder that comes with CiviCRM.

**Comment by eileenmcnaughton** [comment]
I'm afraid it's not UI-configurable - although I think you can add them through the api using api explorer (there just hasn't been an admin UI built)

**Comment by bkeevil** [comment]
OK I figured out how to set them using the API Explorer. I activated MapQuest by setting is_active=1

What is the weight field? The lowest value has priority or the highest?

**Comment by eileenmcnaughton** [comment]
low weight high priority
