### ISSUE TITLE
Error on Guzzle

### ISSUE THREAD

**Issue by edvanleeuwen** [eileenmcnaughton/org.wikimedia.geocoder#21]
If I try to access CiviCRM the first time, I get the following error:

`Error: Call to undefined function GuzzleHttp\Psr7\get_message_body_summary() in GuzzleHttp\Exception\RequestException::getResponseBodySummary() (regel 127 van /home/xxx/domains/xxx.nl/public_html/sites/default/files/civicrm/ext/org.wikimedia.geocoder/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php).`

After refreshing, I am able to use CiviCRM and the geocoding without any problem.

**Comment by eileenmcnaughton** [comment]
@edvanleeuwen which version of Civi - there is a bit of a guzzle compatibility issue

**Comment by eileenmcnaughton** [comment]
We merged the 6.5 version of guzzle to civi core here https://github.com/civicrm/civicrm-core/pull/17551 - it looks like it will ship in 5.28 which I guess drops on Aug 5

**Comment by eileenmcnaughton** [comment]
I guess I could delete guzzle releases 1.4 & 1.5 & do a new 1.6 that specifies civi version 5.28 although I've had trouble deleting releases before

**Comment by edvanleeuwen** [comment]
I have tried upgrading my 5.27.1 test site to 5.28-beta1 and the latest code from here. I now get
`Failed to geocode address, no co-ordinates saved`

No errors in Drupal, Civi or webserver logs.

I'll try to resync my test site with production and give it another try.

**Comment by edvanleeuwen** [comment]
The version is still 1.5. Shouldn't it be 1.6?

**Comment by eileenmcnaughton** [comment]
Hmm maybe - I retagged 1.5 just to try to update the minimum version in the info file because that is the only difference.

That error could just be an address it can't find - I found I couldn't geocode my own address using the way I normally write it....
