### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by bmango** [eileenmcnaughton/org.wikimedia.geocoder#29]
Using php 7.4 I'm getting the error message above. This seems to be coming from line 246 in geocoder.civix.php. I have swapped

```if ($entry{0} == '.') {```

with

```if ($entry[0] == '.') {```

Which I think has fixed it

**Comment by eileenmcnaughton** [comment]
@bmango - I think that is fixed in the master branch?

**Comment by bmango** [comment]
Sorry, apologies!

**Comment by eileenmcnaughton** [comment]
@bmango I tagged release 1.7 against CiviCRM 5.40 - but probably the latest release works fine on older civi versions - I don't check but it's not a rapidly changing code integraion area
