### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by mikemazurkiewicz** [eileenmcnaughton/org.wikimedia.geocoder#3]
Hi,
I have tried to install the org.wikimedia.geocoder extension and keep getting an installation error.
I have Joomla 3.8.13 with CiviCRM 5.6.0. I originally tried this on the 5.4.X versions.

<img width="527" alt="image" src="https://user-images.githubusercontent.com/24593892/46774474-3042a680-ccc8-11e8-97cd-6f7a2095e38b.png">

Any insight would be appreciated.

**Comment by eileenmcnaughton** [comment]
@nicw can you provide some pointers?

**Comment by vingle** [comment]
Hi @mikemazurkiewicz — the installation process is manual.

- Specify/check the location of the extensions directory here: yoursite.org/administrator/?option=com_civicrm&task=civicrm/admin/setting/url&reset=1
(It normally would be yoursite.org/media/civicrm/custom_ext)
- upload the extension there, unzip it (or unzip it first if you are using an FTP client that doesn't let you unzip.
- Refresh the extensions list at yoursite.org/administrator/?option=com_civicrm&task=civicrm/admin/extensions&reset=1 and install and enable it.

For more info, check https://docs.civicrm.org/sysadmin/en/latest/customize/extensions/#joomla

**Comment by shaneonabike** [comment]
Also for what it's worth I had to install API v4 before I could even see this module as I believe it's a requirement. The cool thing is that CiviCRM will already add that to your extension list and you just simply install it!
