### ISSUE TITLE
issue #28 now solved at source

### ISSUE THREAD

**Issue by sebalis** [eileenmcnaughton/org.wikimedia.geocoder#30]
Hi, my pull request geocoder-php/Geocoder#1131 has now been merged which will solve issue #28 if the code is updated. A new release 5.51 has been made at https://github.com/geocoder-php/nominatim-provider so hopefully the change could now be incorporated here. Could you take a look? Thanks :-)

**Comment by eileenmcnaughton** [comment]
Thanks  - I released 1.8 with this fix
