### ISSUE TITLE
Add `getCoordinates`

### ISSUE THREAD

**Issue by eileenmcnaughton** [eileenmcnaughton/org.wikimedia.geocoder#34]
Per https://github.com/civicrm/civicrm-core/pull/23646/files#diff-53bd332a051f691ff2d32cdcc8e703e514704f7bbca4b25205a6e55c96b938feR35 - if we add`getCoordinates` it will allow search kit geocoding

**Comment by agileware-justin** [comment]
Sounds useful :smile:

**Comment by eileenmcnaughton** [comment]
hmm - I wonder if your comment will stay stale-bot i it's tracks - let's see...

**Comment by savionlee** [comment]
Did getCoordinates get implemented? SearchKit console logged a 

```{"error_code":0,"error_message":"Geocoding provider does not support getCoordinates","status":500}```

when i was trying to add a postal code, or city state, the post request logged that error.

![image](https://github.com/eileenmcnaughton/org.wikimedia.geocoder/assets/9041739/0cae77cc-327f-476f-84b6-079548dbc1e2)

**Comment by savionlee** [comment]
Found the pull request #44 that added it after the release of 1.10. Will need to use the git repo or wait for a new release.
