### ISSUE TITLE
Logging for what geocoder is being used?

### ISSUE THREAD

**Issue by zkrebs** [eileenmcnaughton/org.wikimedia.geocoder#4]
I installed the extension successfully and it gives me proximity results just fine. However, I get the error message: "Geocoder quota exceeded. No further geocoding attempts will be made for 60 seconds"

Prior to installation, I had a google maps/google geocoding set up and configured with a new API key I generated. The backend page: /civicrm/a#/geocoders seems to indicate the weight of Google Maps being 1 and Open Street Maps as 2. 

I'm assuming I'm getting the quota limit because the Google proximity search isn't working and it's falling back to OpenStreetMaps. Is this a correct assumption?

**Comment by eileenmcnaughton** [comment]
@zkrebs google has a quota - osm doesn't from memory - they are both enabled?

**Comment by eileenmcnaughton** [comment]
hmm - that should work ....

**Comment by zkrebs** [comment]
I logged on to Google Cloud platform and I do not see any new API calls for the "Maps JavaScript API" so I am assuming that is what Civi or this extension would be using to do the proximity searching? That is what led me to the assumption that it was not using Google

**Comment by zkrebs** [comment]
Cringy. I forgot to turn on the Google Maps geocoding API on their Google Cloud platform settings page for Maps.

**Comment by zkrebs** [comment]
My settings on Google Cloud do not indicate any quotas in place for geocoding API.

Also, I'm seeing this which is concerning.

![image](https://user-images.githubusercontent.com/366418/46829398-8d833a00-cd52-11e8-96de-e5448251db92.png)

**Comment by eileenmcnaughton** [comment]
hmmm

**Comment by eileenmcnaughton** [comment]
what happens if osm is number 1?

**Comment by zkrebs** [comment]
I made OSM weight = 1 and I no longer see the error. 

However, I set up a paid google maps account and I don't think I was over the quota limit?

**Comment by eileenmcnaughton** [comment]
Pehaps it is not picking up your google api settings - it is present in the civicrm_geocoder table?

**Comment by zkrebs** [comment]
Yes the API key is present.  URL is blank. 2018-10-26 22:40:40 is the threshold_last_hit value. We were just updating contacts - doing nothing in large numbers.

**Comment by zkrebs** [comment]
Additionally, it seems like this extension deleted the STATE field for many of my contacts - and the Google geocoder seems to not work properly. Any way I could fix that?

**Comment by eileenmcnaughton** [comment]
@zkrebs fields configured for data_fill should not overwrite if empty. Those configured as 'retained response' fields should - see screenshot

![screenshot 2018-11-13 10 56 44](https://user-images.githubusercontent.com/336308/48377502-e0298a80-e732-11e8-8496-0394e6d1f15f.png)
