### ISSUE TITLE
Open Street Map not activated during a fresh install

### ISSUE THREAD

**Issue by heitzjm** [eileenmcnaughton/org.wikimedia.geocoder#45]
A fresh install does not activate Open Street Map Geocoding Provider anymore (at least in version 1.10).  However, it worked in version 1.8.

The problem might be related to `CRM\Geocoder\Upgrader` : there is no post install function anymore, and the managed entity for OpenStreetMap has `'is_active' => FALSE` in its file. I guess that the post-install hook was responsible for activating OpenStreetMap in version 1.8 because of `'is_enabled_on_install' => TRUE` in the metadata.

The problem occured using a fresh install of Civicrm 5.61.1 and Geocoder 1.10.

**Comment by eileenmcnaughton** [comment]
Hmm - yeah - seems like that should go back. Happy to merge a PR that does that but not sure I'll get back to looking at this for a bit

**Comment by heitzjm** [comment]
I tried to write the PR #46 to solve this issue.

**Comment by heitzjm** [comment]
As requested in PR #46, PR # 46 has been split into three separate PRs : #48 , #49, #50
