### ISSUE TITLE
Civix upgrade for Smarty 3

### ISSUE THREAD

**Issue by nickperkins** [eileenmcnaughton/org.wikimedia.geocoder#59]
This extension requires updating to be able to run using Smarty 3.

The extension currently returns this Notice on every page load in my development civicrm environment:
``` 
Notice: Indirect modification of overloaded property CRM_Core_Smarty::$template_dir has no effect in _geocoder_civix_civicrm_config() (line 107 of sites/default/files/civicrm/ext/org.wikimedia.geocoder/geocoder.civix.php).
```

**Comment by eileenmcnaughton** [comment]
looks like the fix is in master but not a tagged release - I can tag one

**Comment by eileenmcnaughton** [comment]
Closing as I tagged per above - 1.11

**Comment by nickperkins** [comment]
Thank you @eileenmcnaughton. Sorry  I have been offline for a bit. Appreciate the update :)
