### ISSUE TITLE
non-US geocoding via postal code

### ISSUE THREAD

**Issue by mfb** [eileenmcnaughton/org.wikimedia.geocoder#6]
Is non-US geocoding via postal code lookup something you'd be interested in supporting here?  The civicrm_geocoder_zip_dataset database table would need a country column added.

Or should that be a separate provider?

As far as data sources, the good ol' location module for Drupal for example has postal code database for Australia, Belgium, Switzerland, Germany, UK, India, Italy and Norway:  https://cgit.drupalcode.org/location/tree/database

**Comment by eileenmcnaughton** [comment]
@mfb the schema change makes sense - I wouldn't want to ship all the datasets though

**Comment by mfb** [comment]
This isn't actually fixed yet if you want to change the schema.

**Comment by mfb** [comment]
Looks like additional schema changes would be needed.

1. Primary key needs to change to country ID + postal code.
2. Postal code is setup as a char(5) field but would need to be longer.
3. state_code is a US concept - shouldn't it instead link to civicrm_state_province which has name and abbreviation already?
4. The timezone column is weird - shouldn't this be a TZ database identifier such as America/New_York rather than an offset, which changes?

**Comment by mfb** [comment]
@eileenmcnaughton would you be interested in a PR for the above schema changes?

**Comment by eileenmcnaughton** [comment]
@mfb so yes to 1 & 2 -

3 - yeah I guess we can convert that - it's obviously how we received the data & it was easier to use as is but....
4 - timezone is in the schema of civicrm_address - agree it's a bit odd as you say
