### ISSUE TITLE
Geocoder causing error

### ISSUE THREAD

**Issue by SolasSupport** [eileenmcnaughton/org.wikimedia.geocoder#60]
Hi, the Geocoder is producing the following error whenever I try to edit address fields in CiviCRM.

 Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
No PSR-18 clients found. Make sure to install a package providing "psr/http-client-implementation". Example: "php-http/guzzle7-adapter".

Is this an error with the extension itself or something else?

**Comment by clarkac1** [comment]
Similar problem here, users have reported they can't save addresses.  In these cases they are getting the 'Network Error' box and  'Unable to reach the server' which may well be the same issue.

**Comment by alexmarketaccess** [comment]
So glad to see this post, as this is happening on my site too ... any advice on how I revert to Geocoder 1.10 ?

**Comment by clarkac1** [comment]
I am not at my laptop, but here's what I did. I disabled the extension,
which caused a crash. I ignored that and then un-installed it, which
worked. I then cleared caches (in Admin menu) as removing extensions makes
Civicrm generate error messages. Then I removed the extension code from the
folder and replaced it with the 1.10 version which I downloaded from
another site. I then hit refresh and installed the 1.10 version. I had to
the update the geocoder records in the database to make it work, enabling
and disabling active flags as I did before when initially installing
Geocoder as its set up for the US.  Let me know if you need any help if you
hit problems

**Comment by eileenmcnaughton** [comment]
Can you confirm you civi version?

**Comment by clarkac1** [comment]
Yes, for me it's 5.67.3. - sorry should have added that.  BTW I installed 1.11 on 4 sites and all had the same problem (obviously) of not allowing an address update as described above.

**Comment by rgilman** [comment]
5.67.0 for me.

**Comment by eileenmcnaughton** [comment]
OK - it looks like there is a guzzle change in core in 5.69 & the latest geocoder has the version of guzzle for 5.69+ https://github.com/civicrm/civicrm-core/commit/74e05fd9669489a8178b88befc34fa1464b63359

**Comment by eileenmcnaughton** [comment]
I've deleted release 1.11 & replaced it with 1.12 which specifies 5.69 as required

**Comment by clarkac1** [comment]
Thanks, Eileen. I've just checked one of my 5.67.3 sites with 1.10 and it's no longer calling for 1.11 (or 1.12).

**Comment by alexmarketaccess** [comment]
And confirming no request to update on 5.66.0 either. Thanks Eileen!
