### ISSUE TITLE
Geocoding providers

### ISSUE THREAD

**Issue by shaneonabike** [eileenmcnaughton/org.wikimedia.geocoder#8]
Hey thanks for building an amazing module.

I'm not clear how I can enable different Geocoder providers like MapQuest to take the load of geocoding if $oogle or another provider fails. I can see in the main log output which is enabled/not enable, but I'm unclear how to do the rest.

If you give me some guidance I can update the README accordingly

**Comment by eileenmcnaughton** [comment]
fall back between enabled providers happens automatically. Basically if one fails (or is not valid - e.g because of the valid_countries setting) it tries the next enabled one (they are sorted by weight)

 I think you have to configure them using the api rather than an UI though.

**Comment by shaneonabike** [comment]
Yeah I figured that it was related to the order. So when you indicate that it's API related that would mean I would need to write custom code to attach to the module correct?

**Comment by eileenmcnaughton** [comment]
erm - so I mean - I didn't provide a full UI for configuring the processors - you can configure via the api or just by editing the data in the table directly
